"""Summarize E4 JSON outputs into results/E4/README.md."""
import json, os

OUT = "results/E4"
OPS = ["all", "delete-fact", "insert-intermediate", "substitute-predicate", "swap-args", "add-ho"]
SEVS = [1, 2, 3, 4]
M = {
    "MAC": "B4 MAC content vectors",
    "exact": "exact analogy profile +IDF",
    "fp8192": "fingerprint analogy +IDF D=8192",
    "fp1024": "fingerprint analogy +IDF D=1024",
    "C2": "exact C2 relational",
    "C3": "exact C3 WL",
}

def load(kind, tag):
    p = f"{OUT}/{kind}-{tag}.json"
    return json.load(open(p)) if os.path.exists(p) else None

rows = []
for op in OPS:
    for sev in SEVS:
        tag = f"{op}-s{sev}"
        e0, e2 = load("E0", tag), load("E2", tag)
        if not e0 or not e2:
            continue
        m = {x["method"]: x for x in e0["methods"]}
        r = {"op": op, "sev": sev}
        sp = {x["split"]: x for x in e2["splits"]}
        s2 = sp["all"]
        d2 = sp["discriminable"]
        r["disc_n"] = d2["n"]
        r["fac_d"], r["fp_d"], r["fused_d"] = d2["fac_ta_top"], d2["fp_ta_top"], d2["fused_ta_top"]
        r["fused"] = s2["fused_ta_top"]
        r["fp_e2"] = s2["fp_ta_top"]
        for k, name in M.items():
            r[k] = m[name]["all"]["ta_top1"]
            r[k + "_ma"] = m[name]["all"]["win_ta_gt_ma"]
            r[k + "_for"] = m[name]["all"]["win_ta_gt_for"]
        r["fac"] = s2["fac_ta_top"]
        r["corr_r"] = s2["ta_r"]
        r["corr_p"] = s2["ta_p"]
        rows.append(r)

lines = ["# E4: robustness to structural perturbation (summary)", "",
         "Each non-base, non-LS variant (TA, MA, FOR) gets `severity` random operators of the given type, independently. The question is whether the true analogue, now only a *partial* analogue, still outranks the equally perturbed foils. 1,000 groups, 2 distractors, canonical naming, seed 1. Generated by `scripts/e4_sweep.sh`.", "",
         "**TA-top** = P(TA outscores MA, FOR and all RND of its group). FAC = normalized mapper score. Corr. = entity-correspondence precision / recall of base→TA against ground truth.", "",
         "| operator | sev | MAC | C2 exact | C3 exact | analogy exact | **fp D=8192** | fp D=1024 | **FAC** | corr. P / R |",
         "|---|---|---|---|---|---|---|---|---|---|"]
for r in rows:
    lines.append(f"| {r['op']} | {r['sev']} | {r['MAC']:.3f} | {r['C2']:.3f} | {r['C3']:.3f} | {r['exact']:.3f} | **{r['fp8192']:.3f}** | {r['fp1024']:.3f} | **{r['fac']:.3f}** | {r['corr_p']:.3f} / {r['corr_r']:.3f} |")
lines += ["", "## Discriminable groups only", "",
          "A group is *discriminable* if TA still preserves more of the base's higher-order facts (under ground-truth correspondence) than MA and FOR do. Otherwise the perturbation has erased the evidence that made TA the analogue, and no method *should* prefer it. Fused = ½·FAC + ½·fingerprint score.", "",
          "| operator | sev | discriminable | fp D=8192 | FAC | **fused** | fused (all groups) |", "|---|---|---|---|---|---|---|"]
for r in rows:
    lines.append(f"| {r['op']} | {r['sev']} | {r['disc_n']}/1000 | {r['fp_d']:.3f} | {r['fac_d']:.3f} | **{r['fused_d']:.3f}** | {r['fused']:.3f} |")
lines += ["", "Win rates behind TA-top (fingerprint D=8192): P(TA > MA) / P(TA > FOR)", "", "| operator | sev 1 | sev 2 | sev 3 | sev 4 |", "|---|---|---|---|---|"]
for op in OPS:
    cells = []
    for sev in SEVS:
        r = next((x for x in rows if x["op"] == op and x["sev"] == sev), None)
        cells.append(f"{r['fp8192_ma']:.3f} / {r['fp8192_for']:.3f}" if r else "–")
    lines.append(f"| {op} | " + " | ".join(cells) + " |")
open(f"{OUT}/SUMMARY_TABLE.md", "w").write("\n".join(lines) + "\n")
print("\n".join(lines))
